name: paymaya_dart
version: 0.1.0-dev
description: This SDK allows Dart/Flutter applications to accept payments from MasterCard/Visa cardholders via the PayMaya API.
author: Jay Ginete <killertilapia@gmail.com>
homepage: https://github.com/killertilapia/PayMaya-Dart-SDK

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:

dev_dependencies:
